[phases.setup]
nixPkgs = [
  "nodejs_20",
  "libcairo", 
  "libjpeg", 
  "libpng", 
  "pango", 
  "giflib", 
  "fontconfig", 
  "freetype", 
  "harfbuzz",
  "nss", 
  "pixman", 
  "glib", 
  "expat", 
  "dejavu_fonts"
]

[phases.build]
cmds = ["npm install"]

[phases.start]
cmd = "node index.js"
